import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "KageVault",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="min-h-screen bg-navy-deep text-white font-body selection:bg-brand-orange/30 selection:text-white">
        {children}
      </body>
    </html>
  );
}
